/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // AIMS Design System — Corporate Modernism
        'primary':                   '#002141',
        'on-primary':                '#ffffff',
        'primary-container':         '#053664',
        'on-primary-container':      '#7ca0d4',
        'primary-fixed':             '#d4e3ff',
        'primary-fixed-dim':         '#a4c9ff',
        'on-primary-fixed':          '#001c39',
        'on-primary-fixed-variant':  '#204877',
        'inverse-primary':           '#a4c9ff',

        'secondary':                 '#4d6451',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#cce6ce',
        'on-secondary-container':    '#516855',
        'secondary-fixed':           '#cfe9d1',
        'secondary-fixed-dim':       '#b3cdb6',
        'on-secondary-fixed':        '#0a2011',
        'on-secondary-fixed-variant':'#364c3a',

        'tertiary':                  '#002702',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#003f05',
        'on-tertiary-container':     '#69ae5f',
        'tertiary-fixed':            '#abf59d',
        'tertiary-fixed-dim':        '#90d884',
        'on-tertiary-fixed':         '#002202',
        'on-tertiary-fixed-variant': '#0a530f',

        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',

        'surface':                   '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'surface-bright':            '#f8f9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface':                '#0b1c30',
        'on-surface-variant':        '#43474f',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',
        'surface-tint':              '#3b6090',
        'surface-variant':           '#d3e4fe',

        'outline':                   '#737780',
        'outline-variant':           '#c3c6d0',
        'background':                '#f8f9ff',
        'on-background':             '#0b1c30',

        // Brand aliases used in designs
        'aims-navy':                 '#053664',
        'aims-mint':                 '#f1f6f1',
        'aims-mint-card':            '#c1dbc3',
        'aims-mint-border':          '#a8c4aa',
        'aims-orange':               '#eb3b14',
        'forest-green':              '#286b25',
        'soft-mint':                 '#c1dbc3',
        'brand-orange':              '#eb3b14',
        'orange-red':                '#eb3b14',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.5rem',
        lg:      '0.75rem',
        xl:      '1rem',
        '2xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        unit:  '4px',
        xs:    '4px',
        sm:    '8px',
        md:    '16px',
        lg:    '24px',
        xl:    '32px',
        '2xl': '48px',
        gutter:'24px',
        margin:'32px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        code: ['Inter', 'monospace'],
      },
      fontSize: {
        'display-lg':          ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':         ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile':  ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md':         ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg':            ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':             ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':             ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':            ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'code':                ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      boxShadow: {
        'level-1': '0px 1px 3px rgba(0,0,0,0.05), 0px 10px 15px -3px rgba(0,0,0,0.05)',
        'level-2': '0px 20px 25px -5px rgba(0,0,0,0.1)',
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to:   { transform: 'rotate(360deg)' },
        },
        'slide-in-up': {
          from: { transform: 'translateY(100%)', opacity: '0' },
          to:   { transform: 'translateY(0)',    opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to:   { opacity: '0' },
        },
        'accordion-down': {
          from: { height: '0' },
          to:   { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to:   { height: '0' },
        },
      },
      animation: {
        'spin-slow':    'spin-slow 8s linear infinite',
        'slide-in-up':  'slide-in-up 0.5s ease-out forwards',
        'fade-out':     'fade-out 0.5s ease-in 4.5s forwards',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
